For faster loading in main doc, and export
- Pre-crop listings file to be within Greater London Boundaries
- Reduce metrocrime file to Sep 2023
- Subset LSOA to only those in London Boundaries

In [5]:
# Load all libraries [To implement TRY EXCEPT]
import os
from requests import get
from urllib.parse import urlparse
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
import glob

In [ ]:
# Function to download files from remote
def cache_data(src:str, dest:str) -> str:
    """
    Create a folder to store file from URL.
    If folder doesn't already exists, then create one, before writing the file.

    src : URL
    dest : location on local drive
    
    """    
    url = urlparse(src) # We assume that this is some kind of valid URL 
    fn  = os.path.split(url.path)[-1] # Extract the filename
    dfn = os.path.join(dest,fn) #Â Destination filename as path
    
    if not os.path.isfile(dfn):
        
        print(f"{dfn} not found, downloading!")

        path = os.path.split(dest)
        
        if len(path) >= 1 and path[0] != '':
            os.makedirs(os.path.join(*path), exist_ok=True)
            
        with open(dfn, "wb") as file:
            response = get(src)
            file.write(response.content)
            
        print("\tDone downloading...")

    else:
        print(f"Found {dfn} locally!")

    return dfn

In [ ]:
# Define paths
ddir  = os.path.join('data') # destination directory
spath = 'https://github.com/jreades/i2p/blob/master/data/src/' # source path
spath_db = 'https://www.dropbox.com/scl/fi/' # source path for dropbox

# Read in airbnb, crime, and lsoa stats files. https://www.dropbox.com/home/casa/casa_fsds_cheers
# [PATIENCE] Takes about 4 minutes to download and read in the data

crime = pd.read_csv(cache_data(spath_db + 'tcnsqtzoodz3xz1m9gy8i/metrocrime2023.csv?rlkey=od64ji56onhaqobkit3vr5oih&dl=1', ddir),low_memory=False)
listings = pd.read_csv(cache_data(spath_db + '0v2xl5j4l2pvkxfolj5d0/london_listings_sep23.csv.gz?rlkey=feqrd33xwp8zdps2pqa9qzhao&dl=1', ddir),compression='gzip',low_memory=False)
lsoa = gpd.read_file(cache_data(spath_db + 'hda7eykjtjp760s1u4z05/LSOA_Dec_2021_Boundaries_Generalised.geojson?rlkey=9qj5zdxslgxpjshx41988oez1&dl=1', ddir))
water = gpd.read_file(cache_data(spath+'Water.gpkg?raw=true', ddir))
green = gpd.read_file(cache_data(spath+'Greenspace.gpkg?raw=true', ddir))
boros = gpd.read_file(cache_data(spath+'Boroughs.gpkg?raw=true', ddir))
print('Data loaded!')

In [ ]:
# Convert to geodataframes crime incidents, remove invalid geometries
crime = gpd.GeoDataFrame(crime, geometry=gpd.points_from_xy(crime['Longitude'], crime['Latitude']),crs='EPSG:4326')
crime = crime[~crime.geometry.is_empty] # Filtering out no geometry
crime = crime[crime['Month'].isin(['2023-09'])]  # To 95313 rows after filtering only Sep in 2023
print(f'The crime dataset has {crime.shape[0]} rows and {crime.shape[1]} columns.')

# Convert to geodataframes listins, remove invalid geometries
listings = gpd.GeoDataFrame(listings, geometry=gpd.points_from_xy(listings['longitude'], listings['latitude']), crs='EPSG:4326')
listings = listings[~listings.geometry.is_empty] # 87946 rows, no change
print(f'The listings dataset has {listings.shape[0]} rows and {listings.shape[1]} columns.')

In [ ]:
# Reproject everything to British National Grid
boros = boros.to_crs('epsg:27700')
lsoa = lsoa.to_crs('epsg:27700')
crime = crime.to_crs('epsg:27700')
listings = listings.to_crs('epsg:27700')

In [ ]:
# [Takes 3-4 minutes to run] Crop to London boundaries based on only London's LSOA from lsoa_stat   
listings = listings[listings.geometry.within(boros.geometry.unary_union)] # within boundaries
lsoa = lsoa[lsoa['LSOA21CD'].isin(lsoa_stat['LSOA code'].unique())] # LSOA in lsoa_stat (Greater-London-only)
crime = crime[crime['LSOA code'].isin(lsoa_stat['LSOA code'].unique())] # LSOA in lsoa_stat (Greater-London-only)

In [ ]:
# Export to geopackages
crime.to_file(os.path.join(ddir,'dropbox','metrocrime0923.gpkg'),driver='gpkg')
listings.to_file(os.path.join(ddir,'dropbox','london_listings0923.gpkg'), driver='gpkg')
lsoa.to_file(os.path.join(ddir,'dropbox','lsoa_full0923.gpkg'), driver='gpkg')

Concat excel files for LSOA stat into one df, and export

In [2]:
import pandas as pd 
import os 
import glob 
    
# use glob to get all the csv files  
# in the folder 
xlsx_files = glob.glob(os.path.join('data','lsoa_full',"*.xlsx")) 
  
dfs = []
# loop over the list of csv files 
for f in xlsx_files: 
    # read the  file 
    df = pd.read_excel(f,sheet_name='2021') 
    dfs.append(df)

dfs

[      LSOA code local authority code local authority name  All households   \
 0     E01000001            E09000001       City of London              838
 1     E01000002            E09000001       City of London              824
 2     E01000003            E09000001       City of London             1018
 3     E01000005            E09000001       City of London              478
 4     E01032739            E09000001       City of London              882
 ...         ...                  ...                  ...              ...
 4989  E01035718            E09000033          Westminster              732
 4990  E01035719            E09000033          Westminster              634
 4991  E01035720            E09000033          Westminster              587
 4992  E01035721            E09000033          Westminster             1302
 4993  E01035722            E09000033          Westminster             1178

       Detached  Semi-detached  Terraced  Purpose built flat  \
 0            0              3        14                 803
 1            1              2        29                 768
 2            1              0         0                 996
 3            0              0         2                 456
 4            2              7        17                 608
 ...        ...            ...       ...                 ...
 4989        11             30       173                 358
 4990         0              1         1                 624
 4991         2              2        45                 483
 4992         4             22       138                1079
 4993         6              2        29                 858

       Flat in a converted/ shared house (includes all households in shared dwellings)  \
 0                                                    10
 1                                                    16
 2                                                    15
 3                                                    10
 4                                                   152
 ...                                                 ...
 4989                                                148
 4990                                                  8
 4991                                                 48
 4992                                                 35
 4993                                                277

       Flat in a commercial building  \
 0                                 8
 1                                 8
 2                                 6
 3                                10
 4                                96
 ...                             ...
 4989                             11
 4990                              0
 4991                              7
 4992                             23
 4993                              6

       Caravan / other mobile or temporary structure
 0                                                 0
 1                                                 0
 2                                                 0
 3                                                 0
 4                                                 0
 ...                                             ...
 4989                                              1
 4990                                              0
 4991                                              0
 4992                                              1
 4993                                              0

 [4994 rows x 11 columns],
       LSOA code local authority name local authority code  \
 0     E01000001       City of London            E09000001
 1     E01000002       City of London            E09000001
 2     E01000003       City of London            E09000001
 3     E01000005       City of London            E09000001
 4     E01032739       City of London            E09000001
 ...         ...                  ...                  ...
 4989  E01035718          Westminster            E09000033
 4990  E01035719          Westminster            E09000033
 4991  E01035720          Westminster            E09000033
 4992  E01035721          Westminster            E09000033
 4993  E01035722          Westminster            E09000033

       All usual residents  Born in the UK  Aged 0 to 4  Aged 5 to 7  \
 0                    1473             874           34            7
 1                    1382             759           30           20
 2                    1613             921           21            9
 3                    1111             565           31            7
 4                    1607             697           40           11
 ...                   ...             ...          ...          ...
 4989                 2573            1065          100           59
 4990                 1274             535           37           17
 4991                 1218             640           18           16
 4992                 2327            1171           91           42
 4993                 2014             967           66           18

       Aged 8 to 9  Aged 10 to 14  Aged 15   ...  Aged 18 to 19  Aged 20 to 24  \
 0               1             17         5  ...             43            150
 1               8             24         4  ...             55            134
 2              10             24         8  ...             43            159
 3               7             26        14  ...             49            125
 4               4             30        11  ...             93            220
 ...           ...            ...       ...  ...            ...            ...
 4989           20             96        21  ...            258            188
 4990           24             55        24  ...             42            133
 4991           17             23        17  ...             43            139
 4992           19             58        16  ...             71            207
 4993            6             31         5  ...             72            243

       Aged 25 to 29  Aged 30 to 44  Aged 45 to 59  Aged 60 to 64  \
 0               135            151             31              4
 1               141            116             57              2
 2               192            157             33              2
 3                96            119             28              6
 4               207            181             55              5
 ...             ...            ...            ...            ...
 4989            116            215            176             26
 4990            140            155             74              3
 4991            120            109             51              2
 4992            206            277             95              9
 4993            230            245             76              8

       Aged 65 to 74  Aged 75 to 84  Aged 85 to 89  Aged 90 or over
 0                 4              1              0                0
 1                 3              0              0                0
 2                 3              3              0                0
 3                 5              0              0                1
 4                 6              0              0                0
 ...             ...            ...            ...              ...
 4989             17              7              0                1
 4990              4              0              0                0
 4991              1              1              0                0
 4992             17              4              0                0
 4993              8              2              1                0

 [4994 rows x 21 columns],
       LSOA code local authority code local authority name  All households   \
 0     E01000001            E09000001       City of London              835
 1     E01000002            E09000001       City of London              823
 2     E01000003            E09000001       City of London             1013
 3     E01000005            E09000001       City of London              479
 4     E01032739            E09000001       City of London              876
 ...         ...                  ...                  ...              ...
 4989  E01035718            E09000033          Westminster              733
 4990  E01035719            E09000033          Westminster              634
 4991  E01035720            E09000033          Westminster              585
 4992  E01035721            E09000033          Westminster             1303
 4993  E01035722            E09000033          Westminster             1177

       none  one  two  three or more
 0      551  244   28             12
 1      579  204   27             13
 2      825  168   15              5
 3      375   92    9              3
 4      731  114   25              6
 ...    ...  ...  ...            ...
 4989   370  265   75             23
 4990   429  180   21              4
 4991   374  181   28              2
 4992   901  334   58             10
 4993   818  315   37              7

 [4994 rows x 8 columns],
       LSOA code local authority code local authority name  All households   \
 0     E01000001            E09000001       City of London              835
 1     E01000002            E09000001       City of London              827
 2     E01000003            E09000001       City of London             1018
 3     E01000005            E09000001       City of London              479
 4     E01032739            E09000001       City of London              881
 ...         ...                  ...                  ...              ...
 4989  E01035718            E09000033          Westminster              730
 4990  E01035719            E09000033          Westminster              637
 4991  E01035720            E09000033          Westminster              589
 4992  E01035721            E09000033          Westminster             1306
 4993  E01035722            E09000033          Westminster             1178

       No central heating  Gas   Electric  Oil   Solid fuel  \
 0                     22   113       342     2           0
 1                     18    78       358     1           1
 2                     37   449       232     2           0
 3                      7   214        85     3           0
 4                     61   246       489     3           0
 ...                  ...   ...       ...   ...         ...
 4989                  15   413       129     8           0
 4990                  28   313       171     4           0
 4991                  36   293       200     2           0
 4992                  41   684       308     6           1
 4993                  51   574       144    15           0

       Other including communal and renewable   Two or more types
 0                                         283                  73
 1                                         288                  83
 2                                         223                  75
 3                                         134                  36
 4                                          39                  43
 ...                                       ...                 ...
 4989                                       89                  76
 4990                                       85                  36
 4991                                       26                  32
 4992                                      161                 105
 4993                                      323                  71

 [4994 rows x 11 columns],
       LSOA code local authority name local authority code  \
 0     E01000001       City of London            E09000001
 1     E01000002       City of London            E09000001
 2     E01000003       City of London            E09000001
 3     E01000005       City of London            E09000001
 4     E01032739       City of London            E09000001
 ...         ...                  ...                  ...
 4989  E01035718          Westminster            E09000033
 4990  E01035719          Westminster            E09000033
 4991  E01035720          Westminster            E09000033
 4992  E01035721          Westminster            E09000033
 4993  E01035722          Westminster            E09000033

       All Usual residents  United Kingdom  European Union EU14  \
 0                    1478             874                  176
 1                    1382             759                  167
 2                    1613             921                  202
 3                    1098             565                   95
 4                    1621             697                  279
 ...                   ...             ...                  ...
 4989                 2570            1065                  366
 4990                 1271             535                  174
 4991                 1221             640                  222
 4992                 2333            1171                  262
 4993                 2016             967                  280

       Other EU countries  non-EU Europe  Africa  Middle East and Asia  \
 0                     53             61      32                   134
 1                     49             46      44                   171
 2                     68             60      65                   149
 3                     31             22      89                   196
 4                     92             68      40                   259
 ...                  ...            ...     ...                   ...
 4989                  79            155      98                   533
 4990                  41            137      79                   209
 4991                  44             44      63                   135
 4992                  73            108     172                   337
 4993                  60             70      92                   365

       Americas and Caribbean  \
 0                        102
 1                        102
 2                        119
 3                         95
 4                        132
 ...                      ...
 4989                     226
 4990                      79
 4991                      47
 4992                     173
 4993                     134

       Australasia, other Oceania and Other including British Overseas Territories
 0                                                    46
 1                                                    44
 2                                                    29
 3                                                     5
 4                                                    54
 ...                                                 ...
 4989                                                 48
 4990                                                 17
 4991                                                 26
 4992                                                 37
 4993                                                 48

 [4994 rows x 12 columns],
       LSOA code local authority code local authority name  \
 0     E01000001            E09000001       City of London
 1     E01000002            E09000001       City of London
 2     E01000003            E09000001       City of London
 3     E01000005            E09000001       City of London
 4     E01032739            E09000001       City of London
 ...         ...                  ...                  ...
 4989  E01035718            E09000033          Westminster
 4990  E01035719            E09000033          Westminster
 4991  E01035720            E09000033          Westminster
 4992  E01035721            E09000033          Westminster
 4993  E01035722            E09000033          Westminster

       All Usual residents   Disabled; activities limited a lot  \
 0                     1470                                  36
 1                     1385                                  34
 2                     1613                                  75
 3                     1098                                  86
 4                     1624                                  23
 ...                    ...                                 ...
 4989                  2568                                  39
 4990                  1272                                  60
 4991                  1217                                  61
 4992                  2324                                 173
 4993                  2016                                 128

       Disabled; activities limited a little  Not disabled
 0                                       116          1318
 1                                       113          1238
 2                                       145          1393
 3                                       102           910
 4                                        94          1507
 ...                                     ...           ...
 4989                                    150          2379
 4990                                     94          1118
 4991                                     93          1063
 4992                                    196          1955
 4993                                    130          1758

 [4994 rows x 7 columns],
      local authority code local authority name  LSOA code  \
 0               E09000001       City of London  E01000001
 1               E09000001       City of London  E01000002
 2               E09000001       City of London  E01000003
 3               E09000001       City of London  E01000005
 4               E09000001       City of London  E01032739
 ...                   ...                  ...        ...
 4989            E09000033          Westminster  E01035718
 4990            E09000033          Westminster  E01035719
 4991            E09000033          Westminster  E01035720
 4992            E09000033          Westminster  E01035721
 4993            E09000033          Westminster  E01035722

       All usual residents aged 16+ in employment  Less than 2km  \
 0                                            863             84
 1                                            882             78
 2                                           1006            145
 3                                            504             95
 4                                           1179            153
 ...                                          ...            ...
 4989                                         927             61
 4990                                         676             61
 4991                                         680             55
 4992                                        1075             96
 4993                                        1182             84

       2km to less than 5km  5km to less than 10km  10km to less than 20km  \
 0                       53                     34                      11
 1                       40                     21                       6
 2                       80                     60                      22
 3                       78                     45                      27
 4                       77                     48                      14
 ...                    ...                    ...                     ...
 4989                   108                     28                      22
 4990                    86                     40                      16
 4991                   124                     73                       7
 4992                   140                     88                      21
 4993                   189                     74                      11

       20km to less than 30km  30km to less than 40km  40km to less than 60km  \
 0                          1                       2                       3
 1                          2                       4                       3
 2                          3                       0                       0
 3                          4                       0                       2

In [3]:
dfss = [df.set_index('LSOA code') for df in dfs]
merged = pd.concat(dfss, axis=1).reset_index()
merged = merged.loc[:,~merged.columns.duplicated()].copy()

In [4]:
merged.to_csv(os.path.join('data','lsoa_full.csv'),index=False)